### PR TITLE
Fix typo in translate string

### PR DESCRIPTION
**Pull request by WebSpider**
Minor typo causing missing translations

### CODE REVIEW

**Comment by madsi1m** [comment]
@monkeyiq @WebSpider can we update the en_AU to also use `clear_stored_recipients_emails` rather than `clear_stores_recipients_emails` ? Might want to also do pt_BR

**Comment by madsi1m** [comment]
```
#grep -nr clear_stores_recipients_emails
language/pt_BR/lang.php:118:$lang['clear_stores_recipients_emails'] = 'Limpe os e-mails de destinatários armazenados do uso anterior (usado para preencher automaticamente os campos de e-mail).';
language/en_AU/lang.php:119:$lang['clear_stores_recipients_emails'] = 'Clear stored recipients emails from past use (used to automatically complete email fields).';
```

**Comment by madsi1m** [comment]
If i remember correctly the lang files are auto generated yet it still has the old name:
https://github.com/filesender/filesender/blob/4b7e47df6dcbe91a74b329790cd996ec3025c274/language/en_AU/lang.php#L119

**Comment by monkeyiq** [comment]
The json file exported from poeditor contains a blank "" translation for items that have not been entered into poeditor for a language. We could then I guess lookup and import the english baseline term for such terms. The import script currently ignores terms that have no translation so it was skipping `clear_stored_recipients_emails`. I copied the english translation to the en_au on poeditor and now it is importing as expected.

See PR https://github.com/filesender/filesender/pull/2040

Thank you for bringing the issue to my attention.

**Comment by WebSpider** [comment]
We can reconfigure poeditor to send the base language value in case something isnt translated as well, if desired

**Comment by monkeyiq** [comment]
I updated there, a new PR is on the way. It will likely be much less surprising to translators / devops.

**Comment by monkeyiq** [comment]
That becomes quite large... should be a smaller change set over time.

https://github.com/filesender/filesender/pull/2041

**Pull request merged**
