### PR TITLE
python client: allow from_address to be set explicitly

### PR DESCRIPTION
**Pull request by monkeyiq**
This is an attempt to bring in the code from https://github.com/filesender/filesender/pull/1415 to allow the `from_address` to be explicitly set.

### CODE REVIEW

**Comment by monkeyiq** [comment]
This relates to https://github.com/filesender/filesender/issues/1418

**Comment by WebSpider** [comment]
I will see if this works on an install with simplesaml and pseudorandom userids in a few hours

**Comment by monkeyiq** [comment]
Cool. I'm happy to go back and dig some more if it needs an update :)

**Comment by monkeyiq** [comment]
@WebSpider if this PR works for your env I am happy to merge it.

**Comment by WebSpider** [comment]
Just tested this, I am running into the deprecation of `collections.MutableMapping` in python 3.10, it's located in `collections.abc.MutableMapping` these days.

When that is solved, I get a new error:

```
postTransfer
Traceback (most recent call last):
  File "/home/nivo/dev/python-client-update-test/scripts/client/./filesender.py", line 230, in <module>
    transfer = postTransfer(args.username, filesTransfer, args.recipients, subject=args.subject, message=args.message, expires=None, options=[])['created']
  File "/home/nivo/dev/python-client-update-test/scripts/client/./filesender.py", line 153, in postTransfer
    return call(
  File "/home/nivo/dev/python-client-update-test/scripts/client/./filesender.py", line 133, in call
    raise Exception('Http error '+str(code)+' '+response.text)
Exception: Http error 500 {"message":"bad_email","uid":"6486f226cc483","details":null}
```
In the http logs, I can see there still is a new user being created, which then offcourse results in an incorrect API key:

```
[2023-06-12 12:23:34] [rest:debug] /usr/share/filesender/filesender-2.39/www/rest.php:37 RestServer::process() Got "get" request for endpoint "info/" with 0 bytes payload
[2023-06-12 12:23:34] [rest:debug] /usr/share/filesender/filesender-2.39/www/rest.php:37 RestServer::process() Forwarding call to RestEndpointInfo::get() handler
[2023-06-12 12:23:34] [rest:debug] /usr/share/filesender/filesender-2.39/www/rest.php:37 RestServer::process() Got data to send back
[2023-06-12 12:23:34] [rest:info] authentication::create(1) saml_uid db2e82db597c23ab015691dfbf8c89e74e2a4d71
[2023-06-12 12:23:34] [rest:debug] /usr/share/filesender/filesender-2.39/classes/data/Authentication.class.php:137 DBI::prepare(string(SELECT * FROM Authentications WHERE saml_user_identification_uid = :samluid)) DBI call
[2023-06-12 12:23:34] [rest:debug] /usr/share/filesender/filesender-2.39/classes/data/Authentication.class.php:138 (DBIStatement)->execute(array(:samluid => string(db2e82db597c23ab015691dfbf8c89e74e2a4d71))) DBI call
[2023-06-12 12:23:34] [rest:info] authentication::create(2) FOUND AND RETURNING 31
[2023-06-12 12:23:34] [rest:debug] /usr/share/filesender/filesender-2.39/classes/data/User.class.php:281 DBI::prepare(string(SELECT * FROM UserPreferences WHERE authid = :authid)) DBI call
[2023-06-12 12:23:34] [rest:debug] /usr/share/filesender/filesender-2.39/classes/data/User.class.php:282 (DBIStatement)->execute(array(:authid => integer(31))) DBI call
[2023-06-12 12:23:34] [rest:debug] /usr/share/filesender/filesender-2.39/classes/data/User.class.php:210 DBI::prepare(string(SELECT * FROM UserPreferences WHERE id = :id)) DBI call
[2023-06-12 12:23:34] [rest:debug] /usr/share/filesender/filesender-2.39/classes/data/User.class.php:211 (DBIStatement)->execute(array(:id => string(1))) DBI call
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException exception uid:6486f226c7eb9] auth_remote_signature_check_failed
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException trace uid:6486f226c7eb9] #0 /usr/share/filesender/filesender-2.39/classes/auth/Auth.class.php(149): AuthRemote::isAuthenticated()
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException trace uid:6486f226c7eb9] #1 /usr/share/filesender/filesender-2.39/classes/auth/Auth.class.php(279): Auth::user_protected()
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException trace uid:6486f226c7eb9] #2 /usr/share/filesender/filesender-2.39/classes/auth/Auth.class.php(341): Auth::user()
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException trace uid:6486f226c7eb9] #3 /usr/share/filesender/filesender-2.39/classes/rest/RestServer.class.php(80): Auth::isAuthenticated()
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException trace uid:6486f226c7eb9] #4 /usr/share/filesender/filesender-2.39/www/rest.php(37): RestServer::process()
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException trace uid:6486f226c7eb9] #5 {main}
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException details uid:6486f226c7eb9] signed = "post&filesendertest.my.site/rest.php/transfer?remote_user=db2e82db597c23ab015691dfbf8c89e74e2a4d71&timestamp=1686565415&{"from":"db2e82db597c23ab015691dfbf8c89e74e2a4d71","files":[{"name":"dhcp-req.pcap","size":2200}],"recipients":["thatsme@my.site"],"subject":"testje","message":"testje","expires":1688293415,"options":[]}"
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException details uid:6486f226c7eb9] secret = "b306897598810140ad3c4cbc3a9029cbb6fb884c4fe1041XXXNONONO9460e30bb"
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException details uid:6486f226c7eb9] received_signature = "c12073f852c8ab135cdddc9XXXNONONO365fc8983"
[2023-06-12 12:23:34] [rest:error] [AuthRemoteSignatureCheckFailedException details uid:6486f226c7eb9] signature = 1483
```

I am invoking the script with:

```
$ python3 ./filesender.py -v -u db2e82db597c23ab015691dfbf8c89e74e2a4d71 -a API_KEY_FOR_MY_SAML_USER -r thatsme@my.site ~/tmp/dhcp-req.pcap```

**Comment by monkeyiq** [comment]
I think I need to setup a local test environment for this. The PR is still around if anybody is really after this feature.

**Comment by WebSpider** [comment]
Considering the filesender CLI now doesnt work for installs where SAML UID != email address (so anyone with eduPersonTargetedID enabled, for instance), I am after this feature and would love to try again.

I've reopened the PR, and will push a small change to your branch, after which I've verified it to work on both an install with pseudorandom uids and one without.

**Comment by monkeyiq** [comment]
Cool. Verified to work == merging time :)

**Pull request merged**
