### PR TITLE
Cloud: new azure storage backend

### PR DESCRIPTION
**Pull request by monkeyiq**
This code allows storage of files into Azure. There might be different schemas for breaking the file content down, for now each "chunk" of a file is stored in an azure blob and each file becomes a new container of these such blobs.

This code is alpha at this stage. It needs more error handling and testing of what happens in error cases. For example, what the user sees if there is a network error or stall in the backend talking to azure or if azure denies service for any reason.

This code supports upload, download, and on the fly zip64 creation from multiple files in a single download. See the new docs page which should be accessible from the menu in docs.filesender.org for details and information on how to setup your configuration if you wish to test this code.

Testing has only been done against the Azurite server locally at this stage.

### CODE REVIEW

**Comment by kdermody** [comment]
Just to note as I install composer it gives the following warning

```
Package microsoft/azure-storage is abandoned, you should avoid using it. Use microsoft/azure-storage-blob, microsoft/azure-storage-table, microsoft/azure-storage-queue, microsoft/azure-storage-file instead.
```
Testing against Azure rather than Azurite, noting the connection string format is slightly different
FileSender connection string format
```
DefaultEndpointsProtocol=http;AccountName=ACCOUNTNAME;AccountKey=ACCOUNTKEY;BlobEndpoint=http://127.0.0.1:10000/AccountName;
```
Azure connection string format
```
DefaultEndpointsProtocol=https;AccountName=ACCOUNTNAME;AccountKey=ACCOUNTKEY;EndpointSuffix=core.windows.net
```
I've used the FileSender formatting for my tests and added the EndpointSuffix into `cloud_azure_other_settings`

When I run the test scripts I'm getting the following error.
```
root@burly:/opt/filesender/fs20b3/scripts/cloud/azure# php test-azure-simpleblob.php 
PHP Fatal error:  Uncaught InvalidArgumentException: 'container' can't be NULL or empty. in /opt/filesender/fs20b3/optional-dependencies/azure/vendor/microsoft/azure-storage/src/Common/Internal/Validate.php:105
Stack trace:
#0 /opt/filesender/fs20b3/optional-dependencies/azure/vendor/microsoft/azure-storage/src/Blob/BlobRestProxy.php(765): MicrosoftAzure\Storage\Common\Internal\Validate::notNullOrEmpty(NULL, 'container')
#1 /opt/filesender/fs20b3/optional-dependencies/azure/vendor/microsoft/azure-storage/src/Blob/BlobRestProxy.php(747): MicrosoftAzure\Storage\Blob\BlobRestProxy->createContainerAsync(NULL, Object(MicrosoftAzure\Storage\Blob\Models\CreateContainerOptions))
#2 /opt/filesender/fs20b3/scripts/cloud/azure/test-azure-simpleblob.php(65): MicrosoftAzure\Storage\Blob\BlobRestProxy->createContainer(NULL, Object(MicrosoftAzure\Storage\Blob\Models\CreateContainerOptions))
#3 {main}
  thrown in /opt/filesender/fs20b3/optional-dependencies/azure/vendor/microsoft/azure-storage/src/Common/Internal/Validate.php on line 105

```

**Comment by monkeyiq** [comment]
ah ok. I see where this is coming from. Initially I was trying to store everything in a nominated container. Later I moved to creating a container for each file but didn't update the test script.

I will fix this with a future update. But for now you might like to set the following in your config.php file:
```
$config['cloud_azure_container_name'] = 'filesendertest';
```

**Comment by kdermody** [comment]
Yes the test script is working now.

I can also successfully upload/download files to/from azure

Deleting files does not work, throws an error, (trying to delete from local path) and updates the DB as being deleted, but file remains on azure.

Also testing with larger files, tested up to 4GB no problem, then jumped to 16GB and it's having issues. Seems to be trying to delete the file as upload starts, but again deletion doesn't work.

```
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException exception uid:5a840d0d5ee5f] storage_filesystem_cannot_delete
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException trace uid:5a840d0d5ee5f] #0 /opt/filesender/fs20b3/classes/storage/Storage.class.php(205): StorageCloudAzure::deleteFile(Object(File))
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException trace uid:5a840d0d5ee5f] #1 /opt/filesender/fs20b3/classes/data/File.class.php(184): Storage::deleteFile(Object(File))
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException trace uid:5a840d0d5ee5f] #2 /opt/filesender/fs20b3/classes/data/DBObject.class.php(319): File->beforeDelete()
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException trace uid:5a840d0d5ee5f] #3 /opt/filesender/fs20b3/classes/data/Transfer.class.php(804): DBObject->delete()
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException trace uid:5a840d0d5ee5f] #4 /opt/filesender/fs20b3/classes/data/Transfer.class.php(376): Transfer->removeFile(Object(File))
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException trace uid:5a840d0d5ee5f] #5 /opt/filesender/fs20b3/classes/data/DBObject.class.php(319): Transfer->beforeDelete()
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException trace uid:5a840d0d5ee5f] #6 /opt/filesender/fs20b3/classes/rest/endpoints/RestEndpointTransfer.class.php(517): DBObject->delete()
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException trace uid:5a840d0d5ee5f] #7 /opt/filesender/fs20b3/classes/rest/RestServer.class.php(259): RestEndpointTransfer->post()
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException trace uid:5a840d0d5ee5f] #8 /opt/filesender/fs20b3/www/rest.php(37): RestServer::process()
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException trace uid:5a840d0d5ee5f] #9 {main}
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException details uid:5a840d0d5ee5f] path = "/opt/filesender/fs20b3/files/ccf80614-f9c5-6fbe-81ad-116610a3f6c7"
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException details uid:5a840d0d5ee5f] file = "File#33(IST_247.mp4, 17554323209 bytes)"
[2018-02-14 10:18:53] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemCannotDeleteException details uid:5a840d0d5ee5f] transfer = "Transfer#36"
```

**Comment by monkeyiq** [comment]
This is great news! I have added a delete in https://github.com/filesender/filesender/pull/256. It seems I can wipe out the whole container in a single call which works on the local server. 

The deleting of larger files as upload starts is a more challenging bug. Now that things have been seen to work against a real server it might be a good time for me to add some more robust error checking into the upload codepath to see if it is failing for some reason part of the way though the upload transfer.

**Comment by monkeyiq** [comment]
So if 4gb seems to work and 16gb has an issue does 8gb still work? Delete should now work, so if it was trying to delete the 16gb file for some reason maybe now the reason filesender was falling back to delete will also be in the logs?

**Comment by monkeyiq** [comment]
Another experiment might be to set upload_chunk_size to 4 times the size and see if the 16gb upload is ok. This would expose if there was some limitation on the number of blobs being allowed per container, or if we are being throttled in the upload by writing too many blobs in a period of time.  upload_chunk_size and download_chunk_size have to match, I'm putting together a pull request to ensure that now. 

https://docs.microsoft.com/en-us/azure/storage/common/storage-scalability-targets

The code is currently using block blobs and creating them with the data. So I imagine without deconstructing the source behind the API we get a single block in the block blob.  For the default FileSender chunk size of 5mb the 16gb upload would use 3200 blobs.

I will shortly merge https://github.com/filesender/filesender/pull/261 which should give a better indication of why upload fails.

**Comment by kdermody** [comment]
after the latest pull the upload now works with all file sizes

**Comment by monkeyiq** [comment]
Excellent!

**Pull request merged**
