### PR TITLE
Pull out images and make them attachments

### PR DESCRIPTION
**Pull request by madsi1m**
My attempt at getting images in emails to show on most mail clients. Long story short, images need to be attachments.

How it works:
in the email templates set images as:
```
<img src="cid:<name>;<filepath>">
```
Where name is a unique name for the attachment and filepath is the path either absolute or relative to the filesender/www directory
For example:
```
<img src="cid:footerimage;images/footer.png">
```

### CODE REVIEW

**Comment by monkeyiq** [comment]
I am assuming the example code worked ok against gmail :) I will take a look at this shortly.

**Comment by madsi1m** [comment]
gmail + outlook/exchange for the win!

**Comment by monkeyiq** [comment]
I was originally thinking about doing something fancy like this PR to allow automatic image attachments via the cid. One issue here is that at that stage we are processing the html after all lang and other substitutions have occurred. It may be possible at that time to have crafted some data on the page to include an "image" file that was not intended to be attached to the email. 

I have an update to this in  https://github.com/filesender/filesender/pull/1972 

The update requires that images be listed in the config in a new key `template_email_images`. This is an array of `cid -> path`. As this array is in your config one might assume it is a good actor and does not contain paths like `/etc/passwd`.  You can then use the `cid` in your template directly and the mail code checks for an explicit `img src="cid:` tag with only lower characters in the `cid` definition. If that cid is found in the config then the associated image from the config will be attached to the email. The intention is that even in the face of an explicitly nefarious user we will only allow images from paths in the config variable to ever be sent. The path is never in the template, only the value to select the `$cid`. Since the HTML is ok to send as is no update is needed to it, just some matches looking for fairly narrow regexes on an image src tag to find the cids that are of interest.

The config variable is slightly more work but I imagine that images will be fairly few and fairly static over time so it shouldn't be a huge thing to define them in a config variable.

**Comment by madsi1m** [comment]
Closing mine as I prefer yours

**Pull request closed without merging**
