### PR TITLE
storage_filesystem_hashing fixes: use path, nfs volumes, missing directories

### PR DESCRIPTION
**Pull request by monkeyiq**
This fixes a number of issues that seem to have crept into the
storage_filesystem_hashing use. Specifically, files were not stored
into the created subdirectories, NFS support was lacking (df output
would throw an exception), and it seems to have been expected that the
entire subdirectory tree existed in one code path when it is created
on an on demand basis.

There are likely more to come as I retest this functionality but this
is a good first handful of updates.

### CODE REVIEW

**Comment by kdermody** [comment]
After pulling this merge I'm having issues uploading files.

When I "Select FIles" or try drag & drop, nothing happens.

The console in my browser is showing the following error

```
burly.heanet.ie/:31 GET https://burly.heanet.ie/fs20b2/filesender-config.js.php?v=8c7cb446-1513249492 net::ERR_ABORTED
ui.js?v=8c7cb446-1513249492:463 Uncaught TypeError: Cannot read property 'quota' of undefined
    at Object.updateUserQuotaBar (ui.js?v=8c7cb446-1513249492:463)
    at HTMLDocument.<anonymous> (ui.js?v=8c7cb446-1513249492:563)
    at c (jquery-1.9.1.min.js?v=8c7cb446-1513249492:3)
    at Object.fireWith [as resolveWith] (jquery-1.9.1.min.js?v=8c7cb446-1513249492:3)
    at Function.ready (jquery-1.9.1.min.js?v=8c7cb446-1513249492:3)
    at HTMLDocument.H (jquery-1.9.1.min.js?v=8c7cb446-1513249492:3)
updateUserQuotaBar @ ui.js?v=8c7cb446-1513249492:463
(anonymous) @ ui.js?v=8c7cb446-1513249492:563
c @ jquery-1.9.1.min.js?v=8c7cb446-1513249492:3
fireWith @ jquery-1.9.1.min.js?v=8c7cb446-1513249492:3
ready @ jquery-1.9.1.min.js?v=8c7cb446-1513249492:3
H @ jquery-1.9.1.min.js?v=8c7cb446-1513249492:3

```

**Comment by monkeyiq** [comment]
Which browser & version are you using. I just retested git master (which has this merged) with Firefox 57. Doing some more digging.

**Comment by monkeyiq** [comment]
it might not be a browser issue, recent chrome is ok here too.

**Comment by monkeyiq** [comment]
I notice when I load your filesender-config.js.php from here that the logon_url at the end of the page is an open string (no url, no closing '). That value comes from AuthSP::logonURL().

**Comment by monkeyiq** [comment]
This is in turn probably being generated by AuthSPSaml.class.php. Have any of the config settings landing_page, site_url, authentication_source, or simplesamlphp_url changed recently?

**Comment by monkeyiq** [comment]
For reference this is the url from your filesender instance I am testing on 
https://burly.heanet.ie/fs20b2/filesender-config.js.php

that is the URL the browser calls to get public settings like how large the server wants chunks to be during upload, how many terasender threads should be used etc, and the below url to visit to authenticate.

Your filesender-config.js.php is outputting a trailing logon_url which is unterminated at the bottom of the page. For my setup the logon_url is very close to the bottom of the page that filesender-config.js.php gives. So on the upside once that line works there things should fall into place.

I am happy to dig into the code some and try to find out what has broken this for you. The main things that come to mind for things in current master but not in beta2 are working zip64, the updates for filesystem hashing (this pr), I added some configuration validation in the last days too but that will create logs in filesender/logs with verbose information if it is triggering, some small fixes for php7 installations. Though the SAML auth stuff that is generating logon_url shouldn't have changed.

**Comment by kdermody** [comment]
Yes my mistake this does seem to be related to SAML, I can see in the logs now that it can't find a particular class.

```
[Fri Dec 15 09:22:25.276945 2017] [:error] [pid 9701] [client 193.1.228.195:54527] PHP Fatal error:  Uncaught Error: Class 'SimpleSAML_Auth_Simple' not found in /opt/filesender/fs20b2/classes/auth/AuthSPSaml.class.php:216\n
Stack trace:\n
#0 /opt/filesender/fs20b2/classes/auth/AuthSPSaml.class.php(69): AuthSPSaml::loadSimpleSAML()\n
#1 /opt/filesender/fs20b2/classes/auth/AuthSP.class.php(55): AuthSPSaml::isAuthenticated()\n
#2 /opt/filesender/fs20b2/classes/auth/Auth.class.php(107): AuthSP::isAuthenticated()\n
#3 /opt/filesender/fs20b2/classes/utils/Logger.class.php(295): Auth::user()\n
#4 /opt/filesender/fs20b2/classes/utils/Logger.class.php(185): Logger::log('error', 'Looking for cla...')\n
#5 /opt/filesender/fs20b2/classes/autoload.php(116): Logger::error('Looking for cla...')\n
#6 /opt/filesender/fs20b2/classes/autoload.php(169): Autoloader::load('SimpleSAML_Auth...')\n
#7 [internal function]: {closure}('SimpleSAML_Auth...')\n
#8 /opt/filesender/fs20b2/classes/auth/AuthSPSaml.class.php(216): spl_autoload_call('SimpleSAML_Auth...')\n
#9 /opt/filesender/fs20b2/classes/auth/AuthSPSaml.class.php(159): AuthSPSaml::loadSimpleSAML() in /opt/filesender/fs20b2/classes/auth/AuthSPSaml.class.php on line 216, referer: https://burly.heanet.ie/fs20b2/index.php?s=upload
```

I haven't made any changes to SAML related config, and it is still auth'ing me correctly. I'll keep digging here to make sure I didn't break anything.

**Comment by monkeyiq** [comment]
might be useful, for me I have that class defined in 
```
/opt/filesender/simplesamlphp/lib/SimpleSAML/Auth/Simple.php
```
where I have filesender installed in /opt/filesender.

**Comment by kdermody** [comment]
So reverting back to 8e3ab93 all is ok again, but checking out 810f4ee causes the issue. Doing a diff between the versions I don't see anything that might cause it to no longer see the class.

**Comment by monkeyiq** [comment]
does a1fff58c89c3a27288567e16b981e67a7ab08113 work? there was a little update to the class loader in the zip64 code brought in around the a1fff58c89c3a27288567e16b981e67a7ab08113 section. That update should be ok, but it is the closest thought I have to something which might be doing this.

**Comment by kdermody** [comment]
a1fff58 gives the same class issue

**Comment by monkeyiq** [comment]
ok, so doing the below to classes/autoload.php will likely fix the issue:

```
@@ -107,15 +105,8 @@ class Autoloader {
                 $file .= '.class.php';
                 
                 if(!file_exists($file)) {
-
-                    $file = FILESENDER_BASE.'/lib/'.$path;
-                    if(!$path || substr($path, -1) == '/') $file .= str_replace('\\','/',$class);
-                    $file .= '.php';
-
-                    if(!file_exists($file)) {
-                        Logger::error('Looking for class '.$class.', expecting it at '.$file.' but nothing found, may (or may not) be a problem ...');
-                        return;
-                    }
+                    Logger::debug('Looking for class '.$class.', expecting it at '.$file.' but nothing found, may (or may not) be a problem ...');
+                    return;
                 }
```

**Comment by kdermody** [comment]
Yes working as expected now

thanks!

**Comment by monkeyiq** [comment]
cool. I'll roll a PR to make master do this so it works going forward.

**Comment by monkeyiq** [comment]
that is in master now.

**Comment by kdermody** [comment]
Sorry for delayed reaction, but I'm still having the same issues with the Master now.

filesender-config.js.php isn't loading correctly because it can't find the SimpleSAML_Auth_Simple class

For reference, I too have filesender installed in /opt/filesender, but I install simplesamlphp in /opt/simplesamlphp, I don't have them nested.

**Comment by madsi1m** [comment]
Hi, I think I had this issue too. Will check tomorrow on what I did to fix it, if it was the same problem.

Michael D’Silva
Software Engineer
AARNet, Level 1, 62 Lygon St | Carlton South VIC 3053 | Australia<x-apple-data-detectors://0/1> | M. +61 403191855<tel:+61%20403191855> | E. michael.dsilva@aarnet.edu.au<mailto:michael.dsilva@aarnet.edu.au>
Australia's Academic and Research Network
www.aarnet.edu.au<http://www.aarnet.edu.au/>
On 3 Jan 2018, at 21:11, kdermody <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for delayed reaction, but I'm still having the same issues with the Master now.

filesender-config.js.php isn't loading correctly because it can't find the SimpleSAML_Auth_Simple class

For reference, I too have filesender installed in /opt/filesender, but I install simplesamlphp in /opt/simplesamlphp, I don't have them nested.

**Comment by madsi1m** [comment]
Not sure if this relates to you or not. For us i had to put in a copy of sspmod_redis_Store_Redis.php in /filesender/lib/utils/

**Comment by monkeyiq** [comment]
Hi,
  I have switched my local setup over to using simplesamlphp from outside the filesender tree, in /opt/simplesamlphp to chase down what is different in our configurations. To do this I updated my config/config.php file to the new location and updated the httpd config to serve from there. Better for me to show my config in full.

```
# grep auth_sp_saml_simplesamlphp_location config.php
...
$config['auth_sp_saml_simplesamlphp_location'] ='/opt/simplesamlphp/';
...

# cat /etc/httpd/conf.d/filesender.conf 
Alias /simplesaml /opt/simplesamlphp/www
Alias /simplesamlphp /opt/simplesamlphp/www
<Directory "/opt/simplesamlphp/www">
        Options +FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

Alias /filesender /opt/filesender/www
<Directory "/opt/filesender">
        Options +FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>
```

  I am running simplesamlphp-1.14.14, I will test with the latest 1.15 some time soon. 
Which version of  simplesamlphp are you using? 

The saml class loading seems to be setup using the following file. If I move that file away then filesender doesn't load anymore. 

```
/opt/simplesamlphp/lib/_autoload.php
```

I thought it best to put this up to make sure we are running similar versions of the saml and the same locations. I am running filesender git c623b930bffd56ce88409a2df91fe6f0502847b2

**Comment by kdermody** [comment]
I've tested with 
SimpleSAMLphp 1.11
SimpleSAMLphp 1.15
installing SimpleSAMLphp in both /opt/ and /opt/filesender/

All give the same issue. 

This is with c623b930bffd56ce88409a2df91fe6f0502847b2

**Comment by monkeyiq** [comment]
I managed to get a similar break in loading my filesender-config.js.php here by mangling $config['auth_sp_saml_simplesamlphp_location'] to the real path plus some extra characters. By "similar break" I mean that filesender-config.js.php stops output at the logon_url variable.

Could there be a permissions issue or selinux denial or some such on the /opt/simplesamlphp/ or children paths?

I will dig more into this tomorrow Aus time.

**Comment by monkeyiq** [comment]
I have also created https://github.com/filesender/filesender/issues/212 to improve the error reporting when the simplesamlphp/lib/_autoload.php isn't found or isn't readable etc.

**Comment by monkeyiq** [comment]
I've added some more checks with https://github.com/filesender/filesender/pull/213 which might help work out where things are falling over. 

I also upgraded to simplesamlphp-1.15.0 and setup an exampleauth:UserPass to test with. This *might* be an issue that I do most of my testing with these simple user/pass combos because I don't have a real saml server on the local LAN.

I'm on php 7.1 and latest Fedora. Using saml in /opt/simplesamlphp
```
[root@here ~]# cat /etc/fedora-release 
Fedora release 27 (Twenty Seven)
[root@here ~]# php --version
PHP 7.1.12 (cli) (built: Nov 22 2017 06:09:38) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by kdermody** [comment]
A slight change now, in that it's now 'SimpleSAML_Configuration' which cannot be found.

PHP7.0 / Ubuntu 16.04 / saml in the filesender dir (also tried outside)

```
root@burly:/opt/filesender/fs20b2# lsb_release -a
Description:	Ubuntu 16.04.3 LTS
Codename:	xenial
root@burly:/opt/filesender/fs20b2# php --version
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```
```
APACHE ERROR LOG
[Fri Jan 05 09:46:34.507630 2018] [:error] [pid 50451] [client 193.1.228.195:58695] PHP Fatal error:  Uncaught Error: Class 'SimpleSAML_Configuration' not found in /opt/filesender/fs20b2/classes/auth/AuthSPSaml.class.php:233\nStack trace:\n
#0 /opt/filesender/fs20b2/classes/auth/AuthSPSaml.class.php(74): AuthSPSaml::loadSimpleSAML()\n
#1 /opt/filesender/fs20b2/classes/auth/AuthSP.class.php(55): AuthSPSaml::isAuthenticated()\n
#2 /opt/filesender/fs20b2/classes/auth/Auth.class.php(107): AuthSP::isAuthenticated()\n
#3 /opt/filesender/fs20b2/classes/utils/Logger.class.php(304): Auth::user()\n
#4 /opt/filesender/fs20b2/classes/utils/Logger.class.php(194): Logger::log('error', 'Looking for cla...')\n
#5 /opt/filesender/fs20b2/classes/autoload.php(111): Logger::error('Looking for cla...')\n
#6 /opt/filesender/fs20b2/classes/autoload.php(163): Autoloader::load('SimpleSAML_Conf...')\n
#7 [internal function]: {closure}('SimpleSAML_Conf...')\n
#8 /opt/filesender/fs20b2/classes/auth/AuthSPSaml.class.php(233): spl_autoload_call('SimpleSAML_Conf...')\n
#9 /opt/filesender/fs20b2/classes/auth/AuthSPSaml.class.php(164): AuthSPSaml::loadSimpleSAML in /opt/filesender/fs20b2/classes/auth/AuthSPSaml.class.php on line 233, referer: https://burly.heanet.ie/fs20b2/index.php?s=upload
```
```
FILESENDER LOG
[2018-01-05 09:45:36] [gui:error] Looking for class SimpleSAML_Configuration, expecting it at /opt/filesender/fs20b2/classes/utils/SimpleSAML_Configuration.class.php but nothing found, may (or may not) be a problem ...
[2018-01-05 09:45:36] [gui:error] Looking for class SimpleSAML_Logger, expecting it at /opt/filesender/fs20b2/classes/utils/SimpleSAML_Logger.class.php but nothing found, may (or may not) be a problem ...
[2018-01-05 09:45:36] [gui:error] Looking for class file, expecting it at /opt/filesender/fs20b2/classes/utils/file.class.php but nothing found, may (or may not) be a problem ...
[2018-01-05 09:45:36] [gui:error] Looking for class SimpleSAML_Auth_Simple, expecting it at /opt/filesender/fs20b2/classes/utils/SimpleSAML_Auth_Simple.class.php but nothing found, may (or may not) be a problem ...
[2018-01-05 09:45:36] [gui:error] Looking for class SimpleSAML_Session, expecting it at /opt/filesender/fs20b2/classes/utils/SimpleSAML_Session.class.php but nothing found, may (or may not) be a problem ...
[2018-01-05 09:45:36] [rest:error] Looking for class SimpleSAML_Configuration, expecting it at /opt/filesender/fs20b2/classes/utils/SimpleSAML_Configuration.class.php but nothing found, may (or may not) be a problem ...
[2018-01-05 09:45:36] [rest:error] Looking for class SimpleSAML_Logger, expecting it at /opt/filesender/fs20b2/classes/utils/SimpleSAML_Logger.class.php but nothing found, may (or may not) be a problem ...
[2018-01-05 09:45:36] [rest:error] Looking for class file, expecting it at /opt/filesender/fs20b2/classes/utils/file.class.php but nothing found, may (or may not) be a problem ...
[2018-01-05 09:45:36] [rest:error] Looking for class SimpleSAML_Auth_Simple, expecting it at /opt/filesender/fs20b2/classes/utils/SimpleSAML_Auth_Simple.class.php but nothing found, may (or may not) be a problem ...
[2018-01-05 09:45:36] [rest:error] Looking for class SimpleSAML_Session, expecting it at /opt/filesender/fs20b2/classes/utils/SimpleSAML_Session.class.php but nothing found, may (or may not) be a problem ...
```

**Comment by monkeyiq** [comment]
The great news is that I somehow managed to get my local setup to do this too! Initial tracking has lead me to the following placement of a call to Auth::user() which mitigates the issue. I've shown the existing code below, including that one new line in classes/auth/AuthSPSaml.class.php should get things working.

```
            // actually bring in the autoload file
            if ((include_once($saml_auto_load_path)) == FALSE) {
                Logger::haltWithErorr('Failed to include SimpleSAMLphp from path ' . $saml_auto_load_path);
            }

            Auth::user();  // add this line

            // grab the version of the library that is in use.
            $samlConfig = SimpleSAML_Configuration::getInstance();
            self::$SimpleSAMLphpVersion = $samlConfig->getVersion();
```

I will be digging into this over the weekend to see exactly where the wires are getting crossed and come up with a smoother solution to merge into master. In the meantime this might get things going.

**Comment by kdermody** [comment]
Yes!

this clears the errors and allows the javascript to load and I can now upload successfully

**Comment by monkeyiq** [comment]
excellent! 

Once I have created and merged the cleaner solution I will link it here so you know when the fix goes into master.

**Comment by monkeyiq** [comment]
https://github.com/filesender/filesender/pull/214 should integrate the changes that the auth::user() was doing but in a much nicer way. It is merged now.

**Pull request merged**
