### PR TITLE
Fix storable exceptions template injection

### PR DESCRIPTION
**Pull request by yent**
Clean potential template injections from user-provided data upon de-serializing storable exceptions

### CODE REVIEW

**Comment by monkeyiq** [comment]
I am wondering if you have deployed this. If there were any regressions in other parts of the system.

**Comment by madsi1m** [comment]
We've deployed this a few weeks ago, no issues so far.

**Comment by yent** [comment]
Same here, deployed in production before I even did the pull request 😄

**Comment by WebSpider** [comment]
We have a functionally equivalent fix in production since end 2022 as well

**Pull request merged**
