### PR TITLE
Update lang.php

### PR DESCRIPTION
**Pull request by vittore**

### CODE REVIEW

**Comment by WebSpider** [comment]
Hello Vittore,

Thanks for your contribution!

Translations for the FileSender project are managed using POEditor, as can be found on https://docs.filesender.org/filesender/v3.0/i18n/

Would you be so kind to enter the translations there, so we can add them to the next build?

Thanks!

**Comment by WebSpider** [comment]
Apologies. The correct link is https://poeditor.com/join/project/eRy7gOnoQh

I will be updating this in the documentation for v3.

**Comment by vittore** [comment]
Perfect. Now waiting access.

Thanks for your support.
v.

Il giorno lun 9 set 2024 alle ore 11:59 WebSpider ***@***.***>
ha scritto:

**Comment by vittore** [comment]
PoeEditor has the italian (IT) translation updated. When the github PHP files will be updated?

v.

**Comment by WebSpider** [comment]
> PoeEditor has the italian (IT) translation updated. When the github PHP files will be updated?
> 
Thats great news!

The GitHub files are normally updated in batch from POEditor just prior to a release.

I will be closing this PR now, as the contents are in POEditor. Thanks for your contribution!

**Pull request closed without merging**
