### PR TITLE
Amend #629 w/ proper fix for #557, as per @fkooman

### PR DESCRIPTION
**Pull request by peter-**
Thanks for catching this @fkooman, all the constants in the two changed files' paths in #629 must have confused me. ;) Hopefully with this PR issue #557 can be closed for good.

### CODE REVIEW

**Comment by fkooman** [comment]
`$b = $_SERVER['HTTP_USER_AGENT'];`

should this be done _after_ the check?

**Comment by peter-** [comment]
@fkooman: Sry, fixed. I haven't really been paying attention, paradoxically due to the triviality of the PR.
@monkeyiq: The failing test seems unrelated.

**Comment by monkeyiq** [comment]
The CI system is not as good as one might like. If one of the selenium test runs fails by itself and you are not deep into db specific code in the PR it is a fairly good indication that it is a CI execution issue rather than a code issue. Both the selenium runs do the same thing but use mysql or postgresql as the backing store just in case there are db issues in the PR.

**Comment by monkeyiq** [comment]
generally the "restart build" button on the travis-ci details link from this page is useful as a first retry in that case. I've just fired that off to see what happens in 15 minutes.

**Comment by peter-** [comment]
I noticed another instance of this in our web server error logs, recently:

```
[Mon May 04 05:17:00.828833 2020] [proxy_fcgi:error] [pid 2642:tid 140379512887040] [client 74.82.47.2:54976] AH01071: Got error '
PHP message: PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/utils/GUI.class.php on line 86
PHP message: PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/utils/GUI.class.php on line 87
PHP message: PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/utils/GUI.class.php on line 92'
```

Caused by a request from a [bot](https://en.wikipedia.org/wiki/Shadowserver#Data_collection):

```
74.82.47.2 - "" [04/May/2020:05:17:00 +0000] "GET / HTTP/1.1" 200 18050 "-" "-"
```

Something like this should do to avoid `browser_is_*` functions from even getting called when there is no UA header:

```diff
diff --git a/classes/utils/GUI.class.php b/classes/utils/GUI.class.php
index fd69f022..3fbdab79 100644
--- a/classes/utils/GUI.class.php
+++ b/classes/utils/GUI.class.php
@@ -94,7 +94,11 @@ class GUI
 
     public static function use_webasm_pbkdf2_implementation()
     {
-        return Utilities::isTrue(GUI::browser_is_ie11() || GUI::browser_is_edge());
+        if (isset($_SERVER['HTTP_USER_AGENT'])) {
+            return Utilities::isTrue(GUI::browser_is_ie11() || GUI::browser_is_edge());
+        } else {
+            return false;
+        }
     }
     
     /**
```
@monkeyiq Do you need another PR for this?

**Pull request merged**
