### PR TITLE
Docker CI workflow

### PR DESCRIPTION
**Pull request by WebSpider**
Adds a CI workflow that runs upon release.
The workflow builds dockerimage defined in /docker/Dockerfile (such as the one in #955 ), and then uploads it to dockerhub

Credentials for dockerhub are assumed to be available as a secret in the organisation or the repository

### CODE REVIEW

**Comment by monkeyiq** [comment]
It seems that the dockerfile will create an image from FILESENDER_VERSION using the released tarball. Does this change if the dockerfile is run from the github release action?

**Comment by WebSpider** [comment]
Those two are not integrated right now. 

I'll push some commits to this branch to make the Dockerfile accept a version during the build process, and the CI to detect/export the version.

**Comment by monkeyiq** [comment]
So I am guessing this is ready to merge now / soon?

**Comment by monkeyiq** [comment]
I will have a discussion with the board as to which account level is desired for running these scripts.

**Comment by WebSpider** [comment]
Well. That wasn't supposed to happen. 
I'll re-implement once we have the board's decision.

**Pull request closed without merging**
