### PR TITLE
Return to original page upon session timeout

### PR DESCRIPTION
**Pull request by makinog3**
When a session times out while a non-upload page is open and I log back on, it takes me to the upload page instead of the originally opened page.

### CODE REVIEW

**Comment by monkeyiq** [comment]
This seems to be a larger patch than was intended?

**Comment by WebSpider** [comment]
I think it was meant to be an issue instead of a PR

**Comment by makinog3** [comment]
Sorry, I had a little trouble while checking.

**Comment by makinog3** [comment]
I can’t fix the trouble soon, and  I'll close.

**Pull request closed without merging**
