### PR TITLE
Allow filenames contain special characters in Unicode

### PR DESCRIPTION
**Pull request by makinog3**
* add '+' in ASCII
    * add special character areas
      ex) MIDDLE DOT : U+30FB
    * convert from PHP to JavaScript for surrogate pairs
      ex) CJK UNIFIED IDEOGRAPHS : U+29E3D, Emoji : U+1F637

### CODE REVIEW

**Comment by WebSpider** [comment]
IIRC, in some configurations filenames are used in the storage on the server filesystem. 
Will this also work if the filesystem doesnt properly support Unicode files?

**Comment by monkeyiq** [comment]
The `$config['storage_type'] = 'filesystem'` will store the file contents in a single file using a uuid as the file name. The filesystemChunked will make a directory with that file uuid as its name and use several files with offset and chunk size in that directory. A quick look at the cloud storage it seems that the uid and offsets are the main locators there too.

**Comment by monkeyiq** [comment]
I am not sure what sort of reason people would do it for but  U+2044 fraction slash might be confused with a `/` and U+205F is a math space might be confused with a regular space. I guess the open question is if we want the default to be accepting wider ranges or if we should suggest this as a config.php option for sites.

**Comment by makinog3** [comment]
Thank you for your comments.
So, in my PRs, the default setting of `valid_filename_regex` in `ConfigDefaults.php` should be dropped and defined in `config.php` to adapt to individual system requirements.
Another one, a fix in `filesender-config.js.php` will correctly convert `valid_filename_regex` when it contains surrogate pairs, and I would like to take the fix.
How about do you think?

**Comment by madsi1m** [comment]
You would be better off setting it in your config.php
Not 100% sure you need to strreplace in the .js.php file

**Comment by monkeyiq** [comment]
I split out the suggestion for updating valid_filename_regex into https://github.com/filesender/filesender/pull/1476 and the surrogate pairs update into https://github.com/filesender/filesender/pull/1477 and merged them. This should cover the suggestions made in this PR.

Please let me know if there are other translation updates to make :)

**Pull request closed without merging**
