### PR TITLE
New Base Class to run Selenium Tests Without need of sauce/sausage

### PR DESCRIPTION
**Pull request by vinnyalvs**
Please view issue #1140 . 

This Pull Request brings in a new class called BasisTest which permits the run without the need of Sauce Labs or the Sausage package.  

 We did not want to break what currently exists, so we created new files instead of replacing old ones.

### CODE REVIEW

**Comment by monkeyiq** [comment]
Thanks for the PR. 

I have a local VM setup to run Selenium tests against using the same code that is used with sauce labs. This uses the older phpunit and the other bridge stuff that sauce uses. I was tempted in the recent github actions update to try to run selenium in docker and do the test suite locally on a GHA. The current downside to doing that was getting failure feedback. It is handy to be able to playback a video some times to see what was failing in the test. The older phpunit currently used in development is less than optimal, but IIRC it was locked by the version of the bridge code used to contact sauce labs.

I have recently updated half of the selenium tests to work on the development3 branch https://github.com/filesender/filesender/pull/1157. I have the other half slated for action soon. As part of that update many tests were updated to check for elements and visibility before progressing rather than just sleep() blindly. Also I made some methods in the SeleniumTest class to do specific actions or to busy wait on some css class becoming visible for example. Long story short there was a fair bit of code updates for the `SeleniumTest.php` base class and the tests themselves. So we may want to avoid duplicates of those files if possible.

Looking at a diff of SeleniumTest.php and BasisTest.php the major change seems to be the base class being `Sauce\Sausage\WebDriverTestCase` and `\PHPUnit_Extensions_Selenium2TestCase` respectively. It seems most of the other blocks could be updated to be conditional, such as the sauce code in `__construct()`.

Would it be reasonable to try to have the github code inherit from `WebDriverTestCase` and a small script which could be run after a git checkout to update that php file to use `PHPUnit_Extensions_Selenium2TestCase` instead? If the script was fairly small it is probably less of a maintenance issue than trying to keep copies of the tests in sync.

Looking at the differences in ConfigurationOptionsTest.php (taken at random) it seems the biggest change is a method name going from byCss() to byCssSelector(). I am wondering if we couldn't use a common method in the base SeleniumTest which uses reflection to forward to the right place (parent class byCss() if a child of WebDriverTestCase and byCssSelector() if a child of PHPUnit_Extensions_Selenium2TestCase.

**Comment by vinnyalvs** [comment]
Thank you for your answer!

What do you think is the best way to conduce this update?  Do you think the best is to do the modifications in the development3 branch with your updates in the SeleniumTest.php base class and the tests? Of course, we could do your suggestions like creating the common method in the base SeleniumTest which uses reflection and the git checkout script. 

But do you think the best is to do this on the 2.X version or with the 3?

**Comment by monkeyiq** [comment]
One question that is probably best to address first is if the goal of running tests locally (without Sauce Labs) is the main objective.  If the use of sauce and an older phpunit can be lived with then we might be best to direct attention towards documenting what is needed to setup a local execution environment. 

I have one such environment but cobbled it together and once it worked I did not remake another one again from scratch and document the process. If this local execution environment is acceptable then I could turn my attention to making public docs for making such setups.

**Comment by vinnyalvs** [comment]
If you could write down the steps to run locally, it would be great. I think a good place for the documentation it's [here](https://docs.filesender.org/filesender/v2.0/dev/testing/). Also, it's needed to update certain parts of the documentation related to tests like [the reference page in FrontEnd tests section](https://docs.filesender.org/filesender/v2.0/admin/reference/#:~:text=real%20unique%20one.-,Frontend%20tests,-Requirements) where it explicitly says that a SauceLabs API key is a requirement.

**Comment by monkeyiq** [comment]
I will propose this documentation update to the FileSender board for the next MoU. The local VM setup documentation will need to have multiple runs from scratch to make sure that I don't accidentally leave anything out that is needed to get fully up to speed.

**Comment by monkeyiq** [comment]
I think since these tests can be run locally already I will close this PR. There are now also tests against 3.x series which makes splitting this way a little less practical.

**Pull request closed without merging**
