### PR TITLE
Encryption support in python client

### PR DESCRIPTION
**Pull request by PaulLocksley**
Hi Team, 
I've been working on the start of encryption support in the python client. This can also work as an example for issues such as [1038](https://github.com/filesender/filesender/issues/1038 ). 

Currently it only supports AES-GCM but I tried to write it in such a way that is easy to expand in the future. 

The user simply specified -e with their desired password much like they do for email address already.

### Changes

There are 3 new imports required, base64 and Enums are from the standard library but the [Cryptography library](https://github.com/pyca/cryptography) is 3rd party

As it is a 3rd party library and may not be present it has been moved so it only impacts users who haven't installed required library but also want to use Encryption. 

There should be no code changes for users who do not use the -e argument. 

### Testing

I've tested several transfers with large files and multiple files with and without encryption. 
The encrypted transfers behave as expected are decrypted by the web client without issue.
The non encrypted transfers behaved as usual.

If you would like anything to change or don't think this is appropriate for the client let me know.

### CODE REVIEW

**Comment by WebSpider** [comment]
Is it your goal to make this compatible with the webclient crypto?

**Comment by PaulLocksley** [comment]
>Is it your goal to make this compatible with the webclient crypto?

As in support all the same cryptography types? If there is a desire, I wanted to put this forward with just a single type before I put more effort into it. 
 
This AES-GCM implementation is able to be decrypted by the web crypto client.
If that is what you mean so its compatible in that way. 

I had a quick look and it looks like AES-GCM is less popular with 5* servers nominating it in filesender-config.js.php compared to the 31 using AES-CBC so that would probably be a good next step.

<sub>* from servers listed in the [known installs list](https://docs.filesender.org/filesender/known-installs).</sub>

**Comment by WebSpider** [comment]
I guess my question could use a bit more explanation, sorry for that :-)

My main question is: When you upload a file using the python client in this PR, will the webclient be able to decrypt it?

A quick review of this PR shows there doesn't seem to be a PDKDF2 implementation in here, so how would the password be communicated, for instance?

**Comment by PaulLocksley** [comment]
>My main question is: When you upload a file using the python client in this PR, will the webclient be able to decrypt it?

Yes. 

The password is communicated via the -e or --encrypted argument, you simply add the password just like you do for recepiant so -e=Password1234!

From the file recipients point of view it just looks like a normal transfer, it works if they put in the correct password and fails if they put in the wrong password with a warning.

 ---------------
PBKDF2 is used in the key generation step, its part of Pythons standard library so that was fairly straight forward. 

I validated the encryption with the following steps:

1. I took snapshots of the IV , Salt and encrypted data from a real transfer. 
2. I saved the undecrypted first chunk of the same transfer. 
3. I then performed the encryption and confirmed the binary data of the file was identical to the expected data.  

For testing I validated with transfers less than chunk size, and 60mb / 100mb multifile transfers to validate chunking encryption behaviour. 

On download the md5 hash's all matched the uploaded files.

--------------------------


Let me know if I have misunderstood any of the requirements.

**Comment by WebSpider** [comment]
Wow, thanks a lot for this contribution, amazing! 🙏

I will take some time this week and test this on filesender!

**Comment by monkeyiq** [comment]
This is looking cool. I like that `encryption_password_hash_iterations_new_files` is respected too!

I will have more of a dig into things in the coming days. I have performed an upload in script and download in browser test. There are a number of tests in the javascript which are in place at the request of an NREN and reviewed by a cryptographer to check the sanity of the assertions from that point of view. I'm not too sure what to do there, if replicating them is needed. One involving overflow by an upload being too large in GCM is definitely worth adding in the python code to ensure no bad things happen. Having another command line method to upload encrypted files is always welcome.

**Comment by monkeyiq** [comment]
It may also be a nice idea to include a more user friendly message if `encryption_key_version_new_files` is not == 3. At the moment it fails with the following if I set the key version to 1:
```
Failed to parse encryption requirements, encryption cannot be supported.
```

**Pull request merged**
