### PR TITLE
Fix to cron.php - Added missing new properties to __get() from StatLog.class.php

### PR DESCRIPTION
**Pull request by belnet-ming**
This should fix cron.php crashing with error no_such_property #557

### CODE REVIEW

**Comment by peter-** [comment]
Thanks, I had tried something like this but that resulted in other errors (SQL errors) so I rolled back (i.e., I don't have my changes around anymore). Your amendment does cause emails to be sent, but also has these issues (on STDOUT when running interactively) -- this is all on `filesender-2.7`:

```sh
# setuidgid php /usr/bin/php -q /opt/filesender/scripts/task/cron.php                                     
PHP Notice:  Undefined property: StatLog::$browser in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$os in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$is_encrypted in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$browser in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$os in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$is_encrypted in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$browser in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$os in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$is_encrypted in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 190
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Trying to get property of non-object in /opt/filesender/classes/utils/Lang.class.php on line 265
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantBrowserType.class.php on line 86
PHP Notice:  Undefined index: HTTP_USER_AGENT in /opt/filesender/classes/data/constants/DBConstantOperatingSystem.class.php on line 110
PHP Fatal error:  Uncaught DBIUsageException: database_access_failure in /opt/filesender/classes/utils/DBI.class.php:280
Stack trace:
#0 /opt/filesender/classes/data/AuditLog.class.php(430): DBI::__callStatic('exec', Array)
#1 /opt/filesender/scripts/task/cron.php(170): AuditLog::cleanup()
#2 {main}
  thrown in /opt/filesender/classes/utils/DBI.class.php on line 280
```

And the following errors are written to the log (near the end):

```syslog
Jul  1 16:28:17 filesender-test : [cron:info] Cron started
Jul  1 16:28:17 filesender-test : [cron:info] Transfer#2 expired, closing it
Jul  1 16:28:17 filesender-test : [cron:info] Event#transfer_expired on Transfer#2
Jul  1 16:28:17 filesender-test : [cron:info] TranslatableEmail uid generation took 1 tries
Jul  1 16:28:17 filesender-test : [cron:warn] Sending mail
Jul  1 16:28:17 filesender-test : [cron:info] Mail#transfer_expired sent to Recipient#2(nonexistent.recipient@example.edu)
Jul  1 16:28:17 filesender-test : [cron:info] Transfer#2 expired
Jul  1 16:28:17 filesender-test : [cron:info] Transfer#3 expired, closing it
Jul  1 16:28:17 filesender-test : [cron:info] Event#transfer_expired on Transfer#3
Jul  1 16:28:17 filesender-test : [cron:info] Transfer#3 expired
Jul  1 16:28:17 filesender-test : [cron:info] Transfer#4 expired, closing it
Jul  1 16:28:17 filesender-test : [cron:info] Event#transfer_expired on Transfer#4
Jul  1 16:28:17 filesender-test : [cron:info] Transfer#4 expired
Jul  1 16:28:17 filesender-test : [cron:info] Transfer#5 expired, closing it
Jul  1 16:28:17 filesender-test : [cron:info] Event#transfer_expired on Transfer#5
Jul  1 16:28:19 filesender-test : [cron:info] Transfer#5 expired
Jul  1 16:28:19 filesender-test : [cron:info] Transfer#6 expired, closing it
Jul  1 16:28:19 filesender-test : [cron:info] Event#transfer_expired on Transfer#6
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#6 expired
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#7 expired, closing it
Jul  1 16:28:21 filesender-test : [cron:info] Event#transfer_expired on Transfer#7
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#7 expired
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#8 expired, closing it
Jul  1 16:28:21 filesender-test : [cron:info] Event#transfer_expired on Transfer#8
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#8 expired
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#9 expired, closing it
Jul  1 16:28:21 filesender-test : [cron:info] Event#transfer_expired on Transfer#9
Jul  1 16:28:21 filesender-test : [cron:info] TranslatableEmail uid generation took 1 tries
Jul  1 16:28:21 filesender-test : [cron:warn] Sending mail
Jul  1 16:28:21 filesender-test : [cron:info] TranslatableEmail uid generation took 1 tries
Jul  1 16:28:21 filesender-test : [cron:warn] Sending mail
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#9 expired
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#11 expired, closing it
Jul  1 16:28:21 filesender-test : [cron:info] Event#transfer_expired on Transfer#11
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#11 expired
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#13 expired, closing it
Jul  1 16:28:21 filesender-test : [cron:info] Event#transfer_expired on Transfer#13
Jul  1 16:28:21 filesender-test : [cron:info] Transfer#13 expired
Jul  1 16:28:21 filesender-test : [cron:info] Guest#1(nonexistent.recipient@example.net) expired and before guests_expired_lifetime so deleting it
Jul  1 16:28:21 filesender-test : [cron:info] Guest#2(nonexistent.recipient@example.org) expired and before guests_expired_lifetime so deleting it
Jul  1 16:28:21 filesender-test : [cron:info] Guest#3(nonexistent.recipient@example.com) expired and before guests_expired_lifetime so deleting it
Jul  1 16:28:21 filesender-test : [cron:info] Cleaning statlogs
Jul  1 16:28:21 filesender-test : [cron:info] Statlog keeping set to infinite, nothing to clean
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException exception uid:5d1a34a5d788d] database_access_failure
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException trace uid:5d1a34a5d788d] #0 /opt/filesender/classes/data/AuditLog.class.php(430): DBI::__callStatic('exec', Array)
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException trace uid:5d1a34a5d788d] #1 /opt/filesender/scripts/task/cron.php(170): AuditLog::cleanup()
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException trace uid:5d1a34a5d788d] #2 {main}
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d] "SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "au"#012LINE 1: delete au from AuditLogs as au   join auditlogsview al on al...#012               ^"
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d] Array
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d] (
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d]     [name] => exec
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d]     [args] => Array
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d]         (
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d]             [0] => delete au from AuditLogs as au   join auditlogsview al on al.id = au.id   left outer join Guests g   on g.id = al.target_id_as_number    where al.target_type = 'Guest' and g.id is null
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d]         )
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d]
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d] )
Jul  1 16:28:21 filesender-test : [cron:error] [DBIUsageException details uid:5d1a34a5d788d]
```

**Comment by belnet-ming** [comment]
Oups.
Forgot to add the new properties on this commit... My bad.
Added them with commit d598186
This should fix the following messages:
```
PHP Notice:  Undefined property: StatLog::$browser in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$os in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$is_encrypted in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$browser in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$os in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$is_encrypted in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$browser in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$os in /opt/filesender/classes/data/StatLog.class.php on line 365
PHP Notice:  Undefined property: StatLog::$is_encrypted in /opt/filesender/classes/data/StatLog.class.php on line 365
```

As for your error message message, this is linked to the class AuditLog, the function cleanup()
```
            ""
           ."delete au from ".self::getDBTable()." as au"
           ."   join ".self::getViewName()." al on al.id = au.id"
           ."   left outer join ".Guest::getDBTable()." g"
           ."   on g.id = al.target_id_as_number "
           ."   where al.target_type = 'Guest' and g.id is null"
```
I think there is a typo with the first "au" which should be "au.id" ?
I have to test that...

**Comment by belnet-ming** [comment]
Hum... what kind of DB server are you running ?
MySQL/MariaDB or postgresql ? Which version ?
I can't reproduce your error.

**Comment by peter-** [comment]
> MySQL/MariaDB or postgresql ? Which version ?
> I can't reproduce your error.

Fresh install on Debian 9 w/ PostgreSQL 10 from upstream packages (since the Filesender docs mention pg10 as minimum version and Debian 9 only has pg9.6):

```sh
$ apt-cache policy postgresql-10
postgresql-10:
  Installed: 10.9-1.pgdg90+1
  Candidate: 10.9-1.pgdg90+1
  Version table:
 *** 10.9-1.pgdg90+1 500
        500 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by belnet-ming** [comment]
Hum...
JOIN is not valid in a DELETE query according to the postgresql documentation.
For PostgreSQL a joined delete is done with DELETE FROM ... USING ...
(https://www.postgresql.org/docs/10/sql-delete.html)

So this SQL query needs to be rewrite/adapted to PostgreSQL syntax.

**Comment by monkeyiq** [comment]
I have updated the SQL in that query to use a subselect in https://github.com/filesender/filesender/pull/602

**Pull request merged**
