### PR TITLE
UI update

### PR DESCRIPTION
**Pull request by WebSpider**
SURF has been working on a UI update for filesender and would like to contribute by giving back.

TRANSLATIONS
The new UI includes new translation strings, the following defaults in en_AU are given:
```php
$lang['ui2_notifications'] = 'Notifications';
$lang['ui2_invite_guest'] = 'Invite someone to send a file';
$lang['ui2_select_files'] = 'Drag or choose file(s) to send';
$lang['ui2_accept_aup_1'] = 'I accept these terms ';
$lang['ui2_accept_aup_2'] = 'when using this service';
$lang['ui2_send_secure'] = 'Send files securely (max 2GB)';
$lang['ui2_add_files'] = 'Add files';
$lang['ui2_files_added'] = 'file(s) added';
$lang['ui2_total_size'] = 'Total size';
$lang['ui2_encryption_status'] = 'End-to-end encryptie is';
$lang['ui2_my_transfers'] = 'My transfers';
$lang['ui2_get_a_link'] = 'Get a link via mail';
$lang['ui2_mode_link'] = 'Create a download link';
$lang['ui2_mode_mail'] = 'Send via mail';
$lang['ui2_or_get_a_link'] = 'or create a download link';
$lang['ui2_or_mode_mail'] = 'or send a link via mail';
$lang['ui2_transfer_deleted'] = 'Transfer deleted';
$lang['ui2_transfer_extend_error'] = 'Something went wrong, transfer cannot be extended';
$lang['ui2_transfer_extend_exhausted'] = 'Transfer cannot be extended any more';
$lang['ui2_transfer_logs'] = 'Transfer logs';
$lang['ui2_all_files_deleted'] = 'All files have been deleted, so the transfer is deleted as well';
$lang['ui2_all_recipients_deleted'] = 'All recipients have been deleted, so the transfer is deleted as well';
$lang['ui2_no_active_transfers'] = 'No active transfers anymore';
$lang['ui2_no_inactive_transfers'] = 'No inactive transfers anymore';
$lang['ui2_show_more'] = 'Show more';
$lang['ui2_show_all'] = 'Show all';
```

### CODE REVIEW

**Comment by monkeyiq** [comment]
Thank you for the updates! I have merged the above with https://github.com/filesender/filesender/pull/836.

To help with merging contributions I will be building scripts that can take the above data format and update the translations on poeditor for specific languages. So for example the language/nl_NL/lang.php file could then be updated and the scripts would take that and update the translations for the Dutch language on poeditor from the lcoal php file. A nice point here is the scripts that currently bring translation from poeditor into the local language/nl_NL/lang.php file again will test that the strings remain the same through a round trip.

It is still planned to manage translations primarily on poeditor. These new scripts will allow for pull requests that change translations to be accepted without requiring a contributor to enter things on poeditor. This does raise a potential issue were people might start translating these strings and how to handle contribution through both the php file and poeditor. For example, if somebody updates the Dutch translation for these strings and then they are to be contributed again in php there might be two slightly different translations. As far as I know these ui2_ translations will be made available for import in English and Dutch so I think those are the only cases that might see editing on poeditor and php files.

**Comment by monkeyiq** [comment]
I have now merged some scripts to allow selective bulk import to poeditor of translations for languages from php files. If there are other ui2 translations strings (and for Dutch?) please let me know either here or by email and I'll bring those strings into poeditor too.

**Comment by WebSpider** [comment]
@monkeyiq Since we are running release 2.15 ourselves, the initial release of the new UI is based on that.
We've always known there would be some merge conflicts, due to the project progressing and here they are :)

**Comment by monkeyiq** [comment]
I think many of the concepts from this PR have been incorporated into https://github.com/filesender/filesender/tree/2021/bootstrap

**Pull request closed without merging**
